name = "Format"
desc = "C, Python, and type-defined numeric and string formatting"
keywords = ["Strings", "Formatting"]
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
license = "MIT"
uuid = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
